name: bleutooth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  google_nav_bar: ^5.0.7
  flutter_secure_storage: ^9.2.4
  anim_search_bar: ^2.0.3
  pretty_gauge: ^1.0.1
  image_picker: ^1.1.2
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
